Aromat/urls.py
from django.contrib import admin
from django.urls import path, include
from report.views import welcome

urlpatterns = [
    path('', welcome, name="welcome"),
    path('admin/', admin.site.urls),
    path('administrator/', include("report.urls")),
    path('seller/', include("seller.urls"))
]

seller/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.seller_login, name='seller_login'),
    path('aromat_sold/', views.aromat_sold, name='aromat_sold'),
    path('aromat_sold_list/', views.aromat_sold_list, name='aromat_sold_list'),
    path('aromat_list_seller/', views.aromat_list_seller, name='aromat_list_seller'),
    path('seller_logout/', views.seller_logout, name='seller_logout'),
]

report/models.py
from django.db import models

# Create your models here.

from django.core.validators import RegexValidator
from django.contrib.auth.hashers import make_password, check_password

class Administrator(models.Model):
    first_name = models.CharField(max_length=30, verbose_name='Имя')
    last_name = models.CharField(max_length=30, verbose_name='Фамилия')
    phone_number = models.CharField(
        max_length=15,
        validators=[RegexValidator(
            regex=r'^8-\d{3}-\d{3}-\d{4}$',
            message='Phone number must be in the format: 8-xxx-xxx-xxxx',
            code='invalid_phone_number'
        )],
        verbose_name='Телефон'
    )
    password = models.CharField(max_length=50, verbose_name='Пароль')

    def __str__(self):
        return f'{self.first_name} {self.last_name}'
    
    def set_password(self, raw_password):
        self.password = make_password(raw_password)
    
    def check_password(self, raw_password):
        return check_password(raw_password, self.password)
    
    class Meta:
        verbose_name = 'Администратор'
        verbose_name_plural = 'Администраторы'
    
class Branch(models.Model):
    cityname = models.CharField(max_length=100, verbose_name="Название города")

    class Meta:
        verbose_name = 'Филиал'
        verbose_name_plural = 'Филиалы'

    def __str__(self):
        return self.cityname

class Aromat(models.Model):
    code = models.CharField(max_length=5, verbose_name='Код')
    name = models.CharField(max_length=255, verbose_name='Название')
    volume = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Объем')
    branch = models.ForeignKey(Branch, on_delete=models.CASCADE, verbose_name='Филиал')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Аромат'
        verbose_name_plural = 'Ароматы'

class Seller(models.Model):
    lastname= models.CharField(max_length=50,  verbose_name='Фамилия')
    firstname = models.CharField(max_length=50, verbose_name='Имя')
    phone_number = models.CharField(
        max_length=15,
        validators=[RegexValidator(
            regex=r'^8-\d{3}-\d{3}-\d{4}$',
            message='Phone number must be in the format: 8-xxx-xxx-xxxx',
            code='invalid_phone_number'
        )],
        verbose_name='Телефон'
    )
    branch = models.ForeignKey(Branch, on_delete=models.CASCADE, verbose_name='Филиал')
    password = models.CharField(max_length=50, verbose_name='Пароль')

    def set_password(self, raw_password):
        self.password = make_password(raw_password)
    
    def check_password(self, raw_password):
        return check_password(raw_password, self.password)

    class Meta:
        verbose_name = 'Продавец'
        verbose_name_plural = 'Продавцы'

class SoldAromat(models.Model):
    seller = models.ForeignKey(Seller, on_delete=models.SET_NULL, null=True)
    code = models.CharField(max_length=5, verbose_name='Код')
    name = models.CharField(max_length=100, verbose_name='Название аромата')
    volume = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Объем', default=0)
    masla = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Масла', default=0)
    paymenttype = models.CharField(max_length=50, verbose_name='Тип оплаты')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Касса', default=0)
    date = models.DateTimeField(verbose_name='Дата')
    sellername = models.CharField(max_length=255, verbose_name='Имя продавца')
    branch = models.ForeignKey(Branch, on_delete=models.CASCADE, verbose_name='Филиал')
    coment = models.CharField(null=True, verbose_name="Комментарий", max_length=5000)

    class Meta:
        verbose_name = 'Проданные ароматы'
        verbose_name_plural = 'Проданные ароматы'

    def __str__(self):
        return f"{self.code} - {self.sellername} - {self.date}"
    

seller/models.py
from django.db import models

# Create your models here.

report/forms.py
from django import forms
from django.core.validators import RegexValidator
from .models import Aromat

class AdminLoginForm(forms.Form):
    phone_number = forms.CharField(
        max_length=15,
        validators=[RegexValidator(
            regex=r'^8-\d{3}-\d{3}-\d{4}$',
            message='Phone number must be in the format: 8-xxx-xxx-xxxx',
        )],
        widget=forms.TextInput(attrs={'placeholder': '8-xxx-xxx-xxxx', 'id': 'phone'}),
        label="Телефон"
    )
    password = forms.CharField(
        max_length=50,
        widget=forms.PasswordInput(attrs={'placeholder': 'Пароль...', 'id': 'password', 'pattern': '(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{6,}'}),
        label="Пароль")

class AromatAddForm(forms.Form):
    CODETYPE_CHOICES = [
        ('M-', 'M (Man)'),
        ('W-', 'W (Women)'),
        ('U-', 'U (Unisex)'),
    ]
    codetype = forms.ChoiceField(
        choices=CODETYPE_CHOICES, 
        label='Тип кода',
        widget=forms.Select(attrs={'id': 'id_codetype'})
    )
    code = forms.CharField(
        max_length=3,
        widget=forms.TextInput(attrs={'placeholder': 'Код...', 'id': 'code'}),
        label="Код")
    aromatname = forms.CharField(
        max_length=255,
        widget=forms.TextInput(attrs={'placeholder': 'Название...', 'id': 'aromatname'}),
        label="Название аромата")
    size = forms.DecimalField(
        widget=forms.NumberInput(attrs={'placeholder': 'Объем...', 'id': 'size', 'min': 0}),
        label="Объем",
        max_digits=10, decimal_places=2)

class SellerRegisterForm(forms.Form):
    lastname = forms.CharField(
        max_length=50,
        widget=forms.TextInput(attrs={'placeholder': 'Фамилия...', 'id': 'lastname'}),
        label="Фамилия")
    firstname = forms.CharField( 
        max_length=50,
        widget=forms.TextInput(attrs={'placeholder': 'Имя...', 'id': 'firstname'}),
        label="Имя")
    phone_number = forms.CharField(
        max_length=15,
        validators=[RegexValidator(
            regex=r'^8-\d{3}-\d{3}-\d{4}$',
            message='Phone number must be in the format: 8-xxx-xxx-xxxx',
        )],
        widget=forms.TextInput(attrs={'placeholder': '8-xxx-xxx-xxxx', 'id': 'phone'}),
        label="Телефон"
    )
    password = forms.CharField(
        max_length=50,
        widget=forms.PasswordInput(attrs={'placeholder': 'Пароль...', 'id': 'password', 'pattern': '(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{6,}'}),
        label="Пароль")

class FilterForm(forms.Form):
    code = forms.CharField(
        max_length=3,
        widget=forms.TextInput(attrs={'id': 'code'}),
        label="Код")
    aromatname = forms.CharField(
        max_length=50,
        widget=forms.TextInput(attrs={'id': 'aromatname'}),
        label="Название аромата")
    
class AromatForm(forms.ModelForm):
    class Meta:
        model = Aromat
        fields = ['code', 'name', 'volume']
    def clean_volume(self):
        volume = self.cleaned_data.get('volume')
        if volume <= 0:
            raise forms.ValidationError('Объем должен быть положительным числом.')
        return volume

seller/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import SellerLoginForm, AromatSoldForm
from report.models import Seller, Aromat, SoldAromat
from django.contrib.auth import logout
from django.utils import timezone
from datetime import date as dt_date
from django.db.models import Sum
from decimal import Decimal, InvalidOperation
from django.core.exceptions import ValidationError

# Create your views here.

def seller_login(request):
    if request.method == 'POST':
        form = SellerLoginForm(request.POST)
        if form.is_valid():
            phone_number = form.cleaned_data['phone_number']
            password = form.cleaned_data['password']
            print("Phone: ", phone_number, "password: ", password)

            try:
                seller = Seller.objects.get(phone_number=phone_number)
                print("Seller: ", seller)
                print(seller.check_password(password))
                if seller.check_password(password):
                    request.session['seller_id'] = seller.id  
                    print("Все успешно")
                    return redirect('aromat_sold_list')
                else:
                    messages.error(request, 'Неверный номер телефона или пароль!')
            except Seller.DoesNotExist:
                messages.error(request, 'Неверный номер телефона или пароль!')
    else:
        form = SellerLoginForm()
    return render(request, 'seller/seller_login.html', {'form': form})


def seller_session(request):
    seller_id = request.session.get('seller_id')
    seller_name = ""
    if seller_id:
        try:
            seller = Seller.objects.get(id=seller_id)
            seller_name = f"{seller.lastname} {seller.firstname}"
        except Seller.DoesNotExist:
            seller = None
    else:
        seller = None
    return seller_name


def aromat_sold(request):
    seller_name = seller_session(request)
    seller_id = request.session.get('seller_id')
    message = None
    if seller_id:
        try:
            seller = Seller.objects.get(id=seller_id)
        except Seller.DoesNotExist:
            return redirect('seller_login')

        branchname = seller.branch
        aromat_objects = Aromat.objects.filter(branch=branchname)
        if request.method == 'POST':
            form = AromatSoldForm(request.POST, branch=branchname)
            if form.is_valid():
                code = form.cleaned_data['code']
                name = form.cleaned_data['name']
                size = form.cleaned_data['size']
                paymenttype = form.cleaned_data['paymenttype']
                price = form.cleaned_data['cost']
                date = timezone.now()
                coment = form.cleaned_data.get('coment', "")
                sellername = seller_name

                try:
                    # Преобразование значений в Decimal и проверка корректности
                    size = Decimal(size)
                    price = Decimal(price)
                    
                    if size <= 0 or price <= 0:
                        raise ValidationError("Размер и цена должны быть положительными числами.")
                    
                    # Проверка наличия аромата по коду
                    aromat = aromat_objects.get(code=code)
                except InvalidOperation:
                    message = "Некорректное значение для размера или стоимости."
                except Aromat.DoesNotExist:
                    message = "Аромат с указанным кодом не найден."
                except ValidationError as ve:
                    message = f"Ошибка валидации: {str(ve)}"
                else:
                    if aromat.volume >= size:
                        volume = aromat.volume - size
                        aromat.volume = volume
                        SoldAromat.objects.create(
                            seller_id=seller_id, code=code, name=name, volume=volume,
                            masla=size, paymenttype=paymenttype, price=price, date=date,
                            sellername=sellername, branch=branchname, coment=coment
                        )
                        message = 'Продажа успешно сохранена!'
                        aromat.save()
                    else:
                        message = "Недостаточное количество товара!"
            else:
                message = "Форма содержит ошибки. Проверьте введенные данные."
        else:
            form = AromatSoldForm(branch=branchname, initial={'date': timezone.now().date(), 'sellername': seller_name})

        aromats = Aromat.objects.filter(branch=branchname)
        return render(request, 'seller/aromat_sold.html', 
                      {"form": form, 'aromats': aromats, "seller_name": seller_name, 'message': message, 'branchname': branchname})
    else:
        return redirect('seller_login')
        


def aromat_sold_list(request):
    seller_name = seller_session(request)
    message = None
    seller_id = request.session.get('seller_id')
    if seller_id:
        code = request.GET.get('code')
        paymenttype = request.GET.get('paymenttype')
        date = request.GET.get('date')
        today = dt_date.today().strftime('%Y-%m-%d')
        aromat_sold_objects = SoldAromat.objects.filter(seller_id=seller_id)
        aromat_sold_objects_not_filter = SoldAromat.objects.filter(seller_id=seller_id)
        seller = Seller.objects.get(id=seller_id)
        branchname = seller.branch

        if code:
            aromat_sold_objects = aromat_sold_objects.filter(code=code)
        if paymenttype:
            aromat_sold_objects = aromat_sold_objects.filter(paymenttype=paymenttype)
        if date:
            aromat_sold_objects = aromat_sold_objects.filter(date__date=date)
        else:
            date = today
            aromat_sold_objects = aromat_sold_objects.filter(date__date=today)

        total_price = aromat_sold_objects.aggregate(Sum('price'))['price__sum'] or 0
        codes = aromat_sold_objects_not_filter.values_list('code', flat=True).distinct()
        paymenttypes = SoldAromat.objects.values_list('paymenttype', flat=True).distinct()
        dates = SoldAromat.objects.values_list('date', flat=True).distinct()
        dates = [d.strftime('%Y-%m-%d') for d in dates]
        context = {
            'seller_name': seller_name,
            'aromat_sold_objects': aromat_sold_objects.order_by('-id'),
            'codes': codes,
            'paymenttypes': paymenttypes,
            'dates': dates,
            'selected_code': code,
            'selected_paymenttype': paymenttype,
            'selected_date': date,
            'total_price': total_price,
            'today': today,
            'branchname': branchname
        }

        return render(request, "seller/aromat_sold_list.html", context)
    else:
        return redirect('seller_login')
    
def aromat_list_seller(request):
    seller_name = seller_session(request)
    seller_id = request.session.get('seller_id')
    
    if seller_id:
        code = request.GET.get('code')
        aromatname = request.GET.get('aromatname')
        aromat_objects = Aromat.objects.all()
        seller = Seller.objects.get(id=seller_id)
        branchname = seller.branch

        if branchname:
            aromat_objects = aromat_objects.filter(branch=branchname)
        if code:
            aromat_objects = aromat_objects.filter(code=code)
        if aromatname:
            aromat_objects = aromat_objects.filter(name__icontains=aromatname)

        codes = Aromat.objects.values_list('code', flat=True).distinct().filter(branch=branchname)
        names = Aromat.objects.values_list('name', flat=True).distinct().filter(branch=branchname)
        context = {
            'seller_name': seller_name,
            'aromat_objects': aromat_objects,
            'codes': codes,
            'names': names,
            'branchname': branchname
        }

        aromat_objects = Aromat.objects.all()

        return render(request, 'seller/aromat_list_seller.html', context)
    else:
        return redirect('seller_login')

def seller_logout(request):
    logout(request)
    return redirect('seller_login')

seller/templates/seller/aromat_list_seller.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Список ароматов</title>
    <link type="image/x-icon" href="{% static 'image/logo.ico' %}" rel="shortcut icon">
    <link type="Image/x-icon" href="{% static 'image/logo.ico' %}" rel="icon">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static "report/aromat_list.css" %}">
    <link rel="stylesheet" href="{% static "report/menu.css" %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

</head>
<body>
    <nav class="col-sm-12 col-md-12 col-lg-12">
        <div  class="wrapper col-sm-12 col-md-12 col-lg-12" id="wrapper">
            <div class="logo-div">
                <div class="logo"><a href="{% url 'aromat_sold_list' %}" title="Главная"></a></div>
                <div class="welcome-text">
                    <span style="font-weight: bold;">Продавец: </span>
                    <span style="font-weight: normal;">{{ seller_name }}</span>
                </div>
            </div>
          <input type="radio" name="slider" id="menu-btn">
          <input type="radio" name="slider" id="close-btn">
          <ul class="nav-links">
            <label for="close-btn" class="btn close-btn"><i class="fas fa-times"></i></label>
            <li><a href="{% url 'aromat_sold_list' %}">Главная</a></li>
            <li><a class="active-nav-links" href="{% url 'aromat_list_seller' %}">Ароматы</a></li>
            <li><a href="{% url 'aromat_sold' %}">Продано</a></li>
            <li><a href="{% url 'seller_logout' %}" class="fas fa-door-open"></a></li>
          </ul>
          <label for="menu-btn" class="btn menu-btn"><i class="fas fa-bars"></i></label>
        </div>
    </nav>
    <div class="body col-sm-12 col-md-12 col-lg-12">
        <div class="branch-div col-sm-12 col-md-12 col-lg-12">
            <div class="branch-div-elements"><b>Ваш филиал: </b>{{ branchname }}</div>
        </div>
        <div class="filter">
            <form method="get" action="{% url 'aromat_list_seller' %}">
                <div class="filter-input">
                    <label for="code">Код</label>
                    <select name="code" id="code">
                        <option value="">Выберите код</option>
                        {% for code in codes %}
                            <option value="{{ code }}">{{ code }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="filter-input">
                    <label for="aromatname">Название аромата</label>
                    <select name="aromatname" id="aromatname">
                        <option value="">Выберите название</option>
                        {% for name in names %}
                            <option value="{{ name }}">{{ name }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="filter-input-button">
                    <button id="button" class="fas fa-filter" type="submit"></button>
                </div>
            </form>
        </div>
        
        <div class="main col-sm-12 col-md-12 col-lg-12">
            <div class="result-table col-sm-12 col-md-12 col-lg-10">
                <table class="styled-table">
                    <thead>
                        <th>Код</th>
                        <th>Название аромата</th>
                        <th>Обьем</th>
                    </thead>
                    <tbody>
                        {% for aromat in aromat_objects %}
                            <tr>
                                <td>{{ aromat.code }}</td>
                                <td>{{ aromat.name }}</td>
                                <td>{{ aromat.volume }}</td>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>
    <script>
        $('#code').select2({
            placeholder: 'Введите код',
            allowClear: true,
            minimumInputLength: 1, // Минимальное количество символов для начала поиска
            dropdownParent: $('#code').parent(), // Установка контейнера для выпадающего списка
            language: {
                inputTooShort: function() {
                    return 'Пожалуйста, введите 1 или более символов';
                }
            }
        });

        $('#aromatname').select2({
            placeholder: 'Введите название',
            allowClear: true,
            minimumInputLength: 1, // Минимальное количество символов для начала поиска
            dropdownParent: $('#aromatname').parent(), // Установка контейнера для выпадающего списка
            language: {
                inputTooShort: function() {
                    return 'Пожалуйста, введите 1 или более символов';
                }
            }
        });
    </script>
</body>
</html>

seller/templates/seller/aromat_sold.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Проданные ароматы</title>
    <link type="image/x-icon" href="{% static 'image/logo.ico' %}" rel="shortcut icon">
    <link type="Image/x-icon" href="{% static 'image/logo.ico' %}" rel="icon">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static "seller/aromat_sold.css" %}">
    <link rel="stylesheet" href="{% static "report/menu.css" %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">

</head>
<body>
    <nav class="col-sm-12 col-md-12 col-lg-12">
        <div  class="wrapper col-sm-12 col-md-12 col-lg-12" id="wrapper">
            <div class="logo-div">
                <div class="logo"><a href="{% url 'aromat_sold_list' %}" title="Главная"></a></div>
                <div class="welcome-text">
                    <span style="font-weight: bold;">Продавец: </span>
                    <span style="font-weight: normal;">{{ seller_name }}</span>
                </div>
            </div>
          <input type="radio" name="slider" id="menu-btn">
          <input type="radio" name="slider" id="close-btn">
          <ul class="nav-links">
            <label for="close-btn" class="btn close-btn"><i class="fas fa-times"></i></label>
            <li><a href="{% url 'aromat_sold_list' %}">Главная</a></li>
            <li><a href="{% url 'aromat_list_seller' %}">Ароматы</a></li>
            <li><a class="active-nav-links" href="{% url 'aromat_sold' %}">Продано</a></li>
            <li><a href="{% url 'seller_logout' %}" class="fas fa-door-open"></a></li>
          </ul>
          <label for="menu-btn" class="btn menu-btn"><i class="fas fa-bars"></i></label>
        </div>
    </nav>
    <div class="body col-sm-12 col-md-12 col-lg-12">
        <div class="branch-div col-sm-12 col-md-12 col-lg-12">
            <div class="branch-div-elements"><b>Ваш филиал: </b>{{ branchname }}</div>
        </div>
        <div class="main col-sm-12 col-md-12 col-lg-12">
            <h2 class="title">Проданные ароматы</h2>
            <div class="input-form col-sm-12 col-md-9 col-lg-6">
                {% if message %}
                    <p>{{ message }}</p>
                {% endif %}
                <form id="myForm" action="{% url 'aromat_sold' %}" method="post">
                    {% csrf_token %}
                    <div class="input-div">
                        {{ form.code.label_tag }}
                        {{ form.code }}
                        {% if form.code.errors %}
                            <div class="error">{{ form.code.errors }}</div>
                        {% endif %}
                    </div>
                    <div class="input-div">
                        {{ form.name.label_tag }}
                        {{ form.name }}
                        {% if form.name.errors %}
                            <div class="error">{{ form.name.errors }}</div>
                        {% endif %}
                    </div>
                    <div class="input-div">
                        {{ form.size.label_tag }}
                        {{ form.size }}
                        {% if form.size.errors %}
                            <div class="error">{{ form.size.errors }}</div>
                        {% endif %}
                    </div>
                    <div class="input-div">
                        {{ form.cost.label_tag }}
                        {{ form.cost }}
                        {% if form.cost.errors %}
                            <div class="error">{{ form.cost.errors }}</div>
                        {% endif %}
                    </div>
                    <div class="input-div">
                        {{ form.paymenttype.label_tag }}
                        {{ form.paymenttype }}
                        {% if form.paymenttype.errors %}
                            <div class="error">{{ form.paymenttype.errors }}</div>
                        {% endif %}
                    </div>
                    <div class="input-div">
                        {{ form.coment.label_tag }}
                        {{ form.coment }}
                        {% if form.coment.errors %}
                            <div class="error">{{ form.coment.errors }}</div>
                        {% endif %}
                    </div>
                    <div class="input-div">
                        <button type="submit" onclick="confirmSubmit()" class="button">Продано</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>
    <script>
    $(document).ready(function() {
        const aromatData = {
            {% for aromat in aromats %}
                '{{ aromat.code }}': '{{ aromat.name }}',
            {% endfor %}
        };

        const aromatDataReverse = {
            {% for aromat in aromats %}
                '{{ aromat.name }}': '{{ aromat.code }}',
            {% endfor %}
        };
        
        $('#id_code').on('change', function() {
            const selectedCode = $(this).val();
            const selectedName = $('#id_name');
            if (aromatData[selectedCode]) {
                selectedName.val(aromatData[selectedCode]);
            } else {
                selectedName.val('');
            }
        });
        
        // Обработчик изменения выбранного названия аромата через Select2
        $('#id_name').on('select2:select', function(e) {
            const selectedName = $(this).val();
            const selectedCode = $('#id_code');
            if (aromatDataReverse[selectedName]) {
                selectedCode.val(aromatDataReverse[selectedName]).trigger('change'); // Добавляем вызов события change
            } else {
                selectedCode.val('').trigger('change'); // Добавляем вызов события change
        }
        });
        
        // Инициализация Select2 для поля выбора кода аромата
        $('#id_code').select2({
            placeholder: 'Введите код аромата',
            allowClear: true,
            minimumInputLength: 1, // Минимальное количество символов для начала поиска
            dropdownParent: $('#id_code').parent(), // Установка контейнера для выпадающего списка
            language: {
                inputTooShort: function() {
                    return 'Пожалуйста, введите 1 или более символов';
                }
            }
        });
    });
    </script>
    

    

    <script>
        function confirmSubmit() {
            if (confirm("Вы уверены, что ввели правильные данные?")) {
                document.getElementById("myForm").submit();
            } else {
                event.preventDefault();
            }
        }
    </script>
</body>
</html>